// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-IwKqtrqSEIzi_-nds_WAHQS_gbzA18',
    appId: '1:586467644709:web:6245e4dc0e6d8e3f02b6cc',
    messagingSenderId: '586467644709',
    projectId: 'authtutorial-dbec5',
    authDomain: 'authtutorial-dbec5.firebaseapp.com',
    storageBucket: 'authtutorial-dbec5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRnmvHxxqhIhcxJLIEPPWqtps6spv-fo',
    appId: '1:586467644709:android:523bf4fe12f4853702b6cc',
    messagingSenderId: '586467644709',
    projectId: 'authtutorial-dbec5',
    storageBucket: 'authtutorial-dbec5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXk8Ie7fiQ6GZG1EM8rXJBxoh26hX6JKw',
    appId: '1:586467644709:ios:dad8d133925aeff402b6cc',
    messagingSenderId: '586467644709',
    projectId: 'authtutorial-dbec5',
    storageBucket: 'authtutorial-dbec5.firebasestorage.app',
    iosBundleId: 'com.example.hervival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXk8Ie7fiQ6GZG1EM8rXJBxoh26hX6JKw',
    appId: '1:586467644709:ios:dad8d133925aeff402b6cc',
    messagingSenderId: '586467644709',
    projectId: 'authtutorial-dbec5',
    storageBucket: 'authtutorial-dbec5.firebasestorage.app',
    iosBundleId: 'com.example.hervival',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-IwKqtrqSEIzi_-nds_WAHQS_gbzA18',
    appId: '1:586467644709:web:9a85735e33d779dd02b6cc',
    messagingSenderId: '586467644709',
    projectId: 'authtutorial-dbec5',
    authDomain: 'authtutorial-dbec5.firebaseapp.com',
    storageBucket: 'authtutorial-dbec5.firebasestorage.app',
  );
}
